### ISSUE TITLE
Chisels&Bits ignore chunk claiming.

### ISSUE THREAD

**Issue by Zaweri** [LatvianModder/FTBUtilities#158]
You can chisel blocks inside claimed land, so it can be used to grief.

Nfinit Presents MMD Public Server pack is the pack's name, we downgraded to 
FTBUtilities-1.9.4-2.1.0-pre1 
and
FTBLib-1.9.4-2.1.0-pre1
after this occurred.

**Comment by AlgorithmX2** [comment]
https://github.com/AlgorithmX2/Chisels-and-Bits/blob/1.10/src/main/java/mod/chiselsandbits/api/EventBlockBitModification.java might help with this.

**Comment by LatvianModder** [comment]
Thanks! This solves many problems on my side.. However, I am going to suggest an event in Forge, pretty much structured the same as your event, probably named ModifyBlockEvent, so that all modders can fire that before modifying block in a custom way (e.g chiseling bits, using gravity gun to pick up blocks, etc)

**Comment by pathways029** [comment]
Have done a bit of testing and tnt next to a claim will destroy blocks as well as creepers. Water poured will also destroy crops.
