### ISSUE TITLE
/ftb edit_config

### ISSUE THREAD

**Issue by pathways029** [LatvianModder/FTBUtilities#205]
/ftb edit_config command crashes client to desktop (pre3)

**Comment by Dijkstra1** [comment]
@pathways029 are you on a server or in single player

**Comment by pathways029** [comment]
Running a whitelisted server using Donutcraft modpack from Atlauncher

**Comment by pathways029** [comment]
Also /ftb team config closes client

**Comment by Dijkstra1** [comment]
Those commands work fine in single player but when it comes to a server you have seen what happens if you want to change configs in game you still but like this /ftb team config config_name value, on bright side you can use tab to get get the configs names and default values util @latvianmodder fix the GUI.

**Comment by ShaCraft** [comment]
The command disconnects client from server on both my servers. One server is default FTB Unstable the other is modded ftb unstable.

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBLib/issues/33
