### ISSUE TITLE
Loaded Chunks for non-ops Unload Immediately on Logoff

### ISSUE THREAD

**Issue by Ommina** [LatvianModder/FTBUtilities#233]
Perhaps related to #232 

Players, regardless of the value set for offline_timer, have their chunks unloaded immediately on disconnection, with the message "Unloading <name> chunks for being offline too long".

> [15:23:45] [Server thread/INFO] [FTBUtilities/]: Unloading Ommina chunks for being offline for too long
> [15:23:45] [Server thread/INFO] [FTBUtilities/]: Unloading Ommina chunks for being offline for too long
> [15:23:45] [Server thread/INFO] [FTBUtilities/]: Unloading Ommina chunks for being offline for too long
> [15:23:45] [Server thread/INFO] [FTBUtilities/]: Unloading Ommina chunks for being offline for too long

One line per chunk loaded.  

Message is not displayed for op'ed characters.

ranks are not enabled.  default_ranks.json is being edited before server start.

FTBU v3.0.0.3
SMP
And forge 12.18.1.2095, just in case.

Edit:

I tried editing default_ranks while the server was running, then issued the reload command.  Did get the "Server reloaded" reply.  However, chunks were still unloaded on disconnection.

**Comment by LatvianModder** [comment]
"One line per chunk loaded"
Oh bother. Imagine what the spam looks like for people with 64 loaded chunks. I will see if I can fix this immidiently

**Comment by scalda** [comment]
This is due to the mod being hard coded to use the default player rank for 24 hours after log off,but instead of 24 hours it's instant. Instead of like the op rank where it is set to -1 which allows it permanently. I have just done loads of testing to work this out after having all my rank configs keep getting wiped out to then learn the rank system doesn't work/implemented yet but the default ranks are being applied via being hard coded.

I hope this makes sense.

regards

scalda

**Comment by Kuktar** [comment]
What is the solution to this. I am experiencing same issue on FTB infinity lite 1.10.2 pack version 1.3.3

**Comment by LatvianModder** [comment]
Hope that pack ever updates mods

**Comment by dna3e8** [comment]
i am playing the direwolf 20 pack. it looked like it has the newest beta build. do i need one of the alpha builds?

I will add version numbers when I get home.
