### ISSUE TITLE
/ftb team config ftbu.fake_players should be set to true by default

### ISSUE THREAD

**Issue by funniray** [LatvianModder/FTBUtilities#303]
You should have fake players set to true by default. People don't know how to change their team's config mainly because /ftb team config will crash people. I had to tell 3 streamers that they had to do /ftb team config ftbu.fake_players true to get their wither spawning machines or automated living wood or whatever. The point is, people don't know how to change their team config. Also, I'm not sure if it is fixed in the latest version, BUT YOU GET AN ERROR TRYING TO JOIN TEAMS IN HERMITPACK. Besides this rant, I hope you fix this. Your mod is filled with bugs and I'm not impressed. Thank you for you time and reading this.

**Comment by LatvianModder** [comment]
Update your mods or go to pack owners, because *at least* as of 3.2.0:
+ Fake players are set true by default ( [See](https://twitter.com/Direwolf20/status/804716445733187584) )
+ /ftb team config doesn't crash
+ "I'm not sure if it is fixed in the latest version" why don't you check before ranting?

Inb4
[!Rant](http://i.imgur.com/jlVKgCt.gif)
