### ISSUE TITLE
Chunk Loading and Claimed Chunk configs missing in 1.10.2-3.2.4 in Direwolf20 1.10 pack

### ISSUE THREAD

**Issue by demfels** [LatvianModder/FTBUtilities#325]
On my server we used Chunk loading and claimed chunks.  We allowed 5000 claimed chunks and 300 loaded chunks.  When we updated the config file completely removed the options to customize this and players are left with broken chunk loading (strange behavior).  What was this removed, is this a defect?

Previous Config:
  "world": {
    "temp": {
      "max_loaded_chunks": 300,
      "max_claimed_chunks": 5000
    },
    "chunk_loading": true,
    "locked_in_dimensions": [
      1,
      0,
      -1
    ],

New Config:
  "world": {
    "chunk_loading": true,
    "blocked_entities": [],
    "chunk_claiming": true,
    "safe_spawn": false,
    "spawn_area_in_sp": false
  },

**Comment by LatvianModder** [comment]
This was removed because of ranks system, but it appears that it isn't working correctly. See, "temp" stands for "temporary". It should be fixed in next version

**Comment by demfels** [comment]
Thanks. I found the new rank config and we were able to make it allow for our claim and loaded standards.

**Comment by Ricket** [comment]
I have also been experiencing chunk loading issues. But not that chunk loading is completely not working, instead it seems to be maybe partially working (and yes the entire area is chunkloaded fully). Like I have an enderman spawner to collect ender pearls and an endergenic generator that consumes ender pearls. I logged in today to find that my generator had consumed all the pearls, which tells me that the spawner had not been running; but the system is definitely set up so that the enderman spawner produces a surplus of pearls (I played many hours yesterday and the system kept at full pearls the whole time). So the chunkloader apparently kept one running but not the other.

**Comment by OldManCraft** [comment]
demfels, would you mind sharing the config as I'm having the same issue. Would love to have a temp fix till he gets a fix out.

**Comment by demfels** [comment]
{
  "player": {
    "ftbu.chunkloader.max_chunks": 500,
    "ftbu.homes.max": 1,
    "ftbu.claims.max_chunks": 5000
  },
  "op": {
    "ftbu.chunkloader.max_chunks": 500,
    "ftbu.homes.max": 1,
    "ftbu.claims.max_chunks": 5000
  }
}

**Comment by LatvianModder** [comment]
You gotta put your configs in ranks.json, in "config":{} of each rank. That is, if the FTBUtilities is at least 3.3.x+ on the server
