### ISSUE TITLE
server crash when one particular player logs on

### ISSUE THREAD

**Issue by mrgreaper** [LatvianModder/FTBUtilities#345]
once the player has crashed the server he can log in again and all is well... but if he logs out and back in again then the server goes down...once its up he can log in again

crash report is particularly unhelpful 

http://pastebin.com/9qsYwGaM

many of us are using ftbu to chunk load and not having any issue so we are stumped

**Comment by demfels** [comment]
We are having similar issues.  It has been particularly hard to troubleshoot.  We are on the newest beta version of the direwolf20 pack which uses 3.2.4

There are two players this happens to.  I suspect it is related to chunks that are suppose to be loaded but are not properly loaded.  Unfortunately i have not been able to get any log/data to assist with find the root cause.

**Comment by mrgreaper** [comment]
@demfels 
The player that was crashing removed his enderio Dimensional Transceivers and crashed no more...another player started to crash after placing the same block
this MAY be the issue ! no idea if its enderio at fault or ftbu but if your crashing players have them and if them removing them fixes the crashes can you report it here https://github.com/Elecs-Mods/ElecCore/issues/86 it will help them to narrow down the issue (hell if it doesnt fix it post to tell them that too)

**Comment by LatvianModder** [comment]
I'll see if I can get that pack to update FTB mods

**Comment by LatvianModder** [comment]
If this is still happening after updating to 3.4.0+, reopen the issue
