### ISSUE TITLE
[Suggestion] Team Chunkloading

### ISSUE THREAD

**Issue by ThomasAunvik** [LatvianModder/FTBUtilities#375]
Currently only 1 player can chunkload that chunk. Well, i also want that chunk to be chunkloaded, but i cant. Beacuse it is occupied by someone else. 

-I wish that we could have multiple players (from the same team) chunkload that one chunk.
or
-Make it possible to have a chunk loaded when any member of team is online.

For example:
-I have an IC2 reactor. Its in the deep dark. I want it to be chunkloaded. It is currently occupied by someone else in the team, but the player is offline. Cant do anything to chunkload it.

**Comment by Yoosk** [comment]
Seems fairly reasonable and would be useful for teams. Seconding this

**Comment by OldDogy** [comment]
In addition every team member should be able to make there chunk private from the rest of the team.
Sometimes we just don't want others messing with our special setups.

And sometimes we just want to give an outsider access to these few chunks someone from the team claimed.
This would require a friend system (I'm thinking of it as { Player <-> Player } ally; like the current {Player <-> Team} ally system.

!! This could be Implemented with the team chunkloading. say that only if your on the same team and friends with that player only then can they chunkload or unload your chunk ? 

This could be even more complex, If the settings are set that chunks are NOT loaded when your offline,
Maybe it can be done so that if your Teammate+Friend is online he also chunkloads your chunks ?
---------------------

Welp that's a couple of suggestions to think about.
Cheers!

**Comment by LatvianModder** [comment]
> -I wish that we could have multiple players (from the same team) chunkload that one chunk.
> or
> -Make it possible to have a chunk loaded when any member of team is online.

First one is essentially impossible, because of coding, but second suggestion is fairly easy to do and I like it

> In addition every team member should be able to make there chunk private from the rest of the team.
> Sometimes we just don't want others messing with our special setups.

Yeah I like this idea, also easy to do (Team owner/mods would be able to interact with chunks though, but protect from other members/allies)

> And sometimes we just want to give an outsider access to these few chunks someone from the team claimed.
> This would require a friend system (I'm thinking of it as { Player <-> Player } ally; like the current {Player <-> Team} ally system.

I like the idea, but it would be very complex to code/save as nbt. Its already a lot of data to save
