### ISSUE TITLE
Ranks and commands

### ISSUE THREAD

**Issue by Gunner76th** [LatvianModder/FTBUtilities#399]
I am wanting to be able to give certain op level commands to a special rank group, but I do not want to have to set the player to OP. My understanding was that with Ranks you could grant any command to that rank, and they would be able to use it, regardless of if they were set as OP at the vanilla level. 
https://pastebin.com/K7P1Zrpi That is a copy of our current ranks setup (still working on fine tuning things for devs and mods). 

As you can see, I did grant him both "+gamemode" and "+command.gamemode 0" to try and test things, and I even tried the following variations: "+command.gamemode" "+gamemode.1" "+command.gamemode.1" 
Unless we set the player to OP at the vanilla level, he is unable to use gamemode. In addition, it seems that we are unable to restrict which gamemodes the player is allowed to use. 

A list of things we would like to be able to do with ranks without having the player be op:

Allow a rank to set only specific gamemodes (Spectator, Survival)
Allow a rank to use the /tp command
Allow a rank to use /profile from the mod tickprofiler

**Comment by LatvianModder** [comment]
Since gamerules aren't registered as subcommands, you can't specify variant. But now this gives me an idea, I could add configurable command substitutes - /spectate means "/gamemode 3", /survival means "/gamemode 0", etc, and you could assign permissions to those new commands. otherwise, all command nodes are ```+command.cmd_name``` or ```+command.tree_cmd_name.subcommand.subcommand```
So you should add (btw spectator mode I think is a bad idea for people to have, because they can teleport anywhere they want, then turn back into players and grief)

```
"+command.gamemode",
"+command.tp",
"+command.profile"
```

**Comment by eobie** [comment]
Do wildcards work with permissions?

as an example...

"-ftbu.claims.item.rftoolsdim.*",

**Comment by LatvianModder** [comment]
Yep

**Comment by eobie** [comment]
great thanks!

**Comment by Mystyfy** [comment]
Running a pixelmon server with ftbu as my claims and permissions mod to try and keep things simple.  I can't for the life of me get permissions to work.  Is the system currently implemented and I'm not using/writing it correctly?  I'm fine with it not suppose to be working :)  I just feel like a moron atm for not getting it to work.  Here is where I'm at currently (thanks in advance for the reply/help if possible):

I'm needing a very simple permission set to test how it all works.  I'm wanting players to be able to interact with the pixelmon pc in claimed chunks that they don't own.  I have edited ranks.json under player with "+ftbu.claims.interact.pixelmon.pc", edited permissions html and txt to allow ALL instead of OP for the same permission.  Have also tried a read only permission on the file so it wouldn't overwrite as well.  I've tried every other combination of what I would assume work to get this one change made.

Side note with the "syntax" option in ranks...is that for chat prefix?  Can't get that working either although when I run a ranks check in console it pulls up the proper rank for the player with the colored prefix but in-game nothing has changed.   I could be totally off on how it all works but I've tried everything I can think of and usually don't have trouble with this type of issue.

The gui claiming and ease of use make the mod great :)  Just wondering if it's all implemented and what I'm trying is pointless or whether I'm doing it wrong...would appreciate any help!!

**Comment by Gunner76th** [comment]
the only way a player can interact with claimed chunks they do not own is
if the chunk owner sets his team to either be open to everyone, ie the
owner must add the players as allies or teammates.  the only broad to this
is to make the players OP on the server.  If I am understanding what you
are wanting, it would break the very security that chunk claiming creates.

On Apr 3, 2017 4:13 PM, "Mystyfy" <notifications@github.com> wrote:

Running a pixelmon server with ftbu as my claims and permissions mod to try
and keep things simple. I can't for the life of me get permissions to work.
Is the system currently implemented and I'm not using/writing it correctly?
I'm fine with it not suppose to be working :) I just feel like a moron atm
for not getting it to work. Here is where I'm at currently (thanks in
advance for the reply/help if possible):

I'm needing a very simple permission set to test how it all works. I'm
wanting players to be able to interact with the pixelmon pc in claimed
chunks that they don't own. I have edited ranks.json under player with
"+ftbu.claims.interact.pixelmon.pc", edited permissions html and txt to
allow ALL instead of OP for the same permission. Have also tried a read
only permission on the file so it wouldn't overwrite as well. I've tried
every other combination of what I would assume work to get this one change
made.

Side note with the "syntax" option in ranks...is that for chat prefix?
Can't get that working either although when I run a ranks check in console
it pulls up the proper rank for the player with the colored prefix but
in-game nothing has changed. I could be totally off on how it all works but
I've tried everything I can think of and usually don't have trouble with
this type of issue.

The gui claiming and ease of use make the mod great :) Just wondering if
it's all implemented and what I'm trying is pointless or whether I'm doing
it wrong...would appreciate any help!!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LatvianModder/FTBUtilities/issues/399#issuecomment-291259823>,
or mute the thread

**Comment by Gunner76th** [comment]
I will upload my ranks.json here in a bit with contents denoting what each
section does. Latvian has helped me understand the json a lot lately.

**Comment by Mystyfy** [comment]
I don't see a simple interaction of an object as a complete loss of security.  It would be very helpful in the situation I'm in atm.  I have regions/towns claimed as the starter area and other npc/gym towns around the map and have them claimed by a specific named user to represent that region (Kanto, Hoenn, etc).  It would be helpful if I could override the use of the pixelmon pc, trade machine, enchanting table, etc as a use to normal player permission.  Not a problem if it won't work - was just hoping to stick with ftbu with its ease of use :)  Thanks for the reply and the json upload here soon, appreciate it!!

**Comment by Gunner76th** [comment]
in that case, just set those teams to be open to everyone.

**Comment by eobie** [comment]
I don't think that's what he wants. He wants to protect the buildings while allowing a player to interact with a specific block within the protected area. I hit the same issue when I build a spawn house. We had to use pressure plates to allow the player in and out because they couldn't interact with the doors. I didn't want to not protect it because then someone could grief the building. I think that's what I'm getting from him as well.

**Comment by Mystyfy** [comment]
Yes indeed :)  Seems like it should be possible given how the files manage ranks/permission and the fact that there are already some permissions that are bypassed (doors and such).  They are all in the config/permission files but editing ranks, files, etc doesn't do squat in actually changing anything outside of the preset block interactions.  It feels as if those exceptions are hard coded into the mod and have nothing to do with the config options atm.  Hopefully it will be an option soon :)  Appreciate the mod and all it has to offer - just trying to minimize the amount of hassle to myself and users for this particular setup and was trying to use FTBU as the primary claim and permission setup.  Thanks for the help so far.

**Comment by LatvianModder** [comment]
@Mystyfy from first comment, sounds like you are doing everything right. Make sure you have enabled ranks and command overrides in config.json

**Comment by Mystyfy** [comment]
So what I'm wanting to do should be possible with FTBU then?  I started fresh with the mod and the settings.  The following is what I have changed in order to try just to enable pixelmon pc interaction within a claimed chunk by another person.

config.json - all options/settings to enable ftbu to do its thing are true
html configs - left them default for now, assuming ranks and permissions set these?
ranks.json - added the +ftbu.claims.interact.pixelmon.pc to the player rank
playerranks.json - left default assuming players are assigned to the player rank
minecraft - had a player claim a chunk and put a pc on it

According to those settings shouldn't a different player be able to interact with the pc on their property?  Let me know if I'm doing something wrong or need to manually set anything.  I'm trying to change as little as possible in order to narrow down where/what is going on.  Thanks!!

**Comment by Mystyfy** [comment]
If its relevant...this is the first version of minecraft I'm attempting to run spongeforge on.  Could that be a possible conflict somewhere?  I have no other mods/plugins that are messing with permissions.  I'm trying to keep things small/smooth atm and have: customnpcs, journeymap, ftbu, pixelmon, pixelmon extras, pixelmon tcg, rtg (real terrain generator), agp (gym plugin for pixelmon), and spongeforge.

**Comment by LatvianModder** [comment]
Definitely spongeforge fault, it won't work well with FTBUtilities. What do you need spongeforge for?

**Comment by LatvianModder** [comment]
The original issue has been solved btw, so closing this
