### ISSUE TITLE
An unknown error occurred while attempting to perform this command.

### ISSUE THREAD

**Issue by voxelv** [LatvianModder/FTBUtilities#404]
Server Log:
https://hastebin.com/usecifadek.vbs

Reproducible:
1. Install FTB Beyond 1.3.0
2. Connect to server
3. Press the Teams GUI button

Minecraft 1.10.2
Pack FTB Beyond 1.3.0

**Comment by Gunner76th** [comment]
1) Please provide a complete crash report when posting bugs. 2) is this an actual crash or a bug that the server continues thorugh? If it is not a crash, then the author will need your server-fml-latest.log file as there may be additional information contained within that will help him understand the nature of the issue. 

In addition, generally mod authors need to know more than just what pack the error is from. Because of the fact that you can manually update files in the pack, he will need to know what version of forge you are running, as well as what version of FTBLib and FTBUtilities.

**Comment by voxelv** [comment]
Unfortunately in haste to revert back to 1.2.1 the logs were lost. I'll close this issue for now and wait for 1.3.1 or later.
