### ISSUE TITLE
Unable to save inventories

### ISSUE THREAD

**Issue by TheBrain0110** [LatvianModder/FTBUtilities#411]
`/ftb inv save` fails with ` [FML]: [Baubles API] Could not invoke baubles.common.lib.PlayerHandler method getPlayerBaubles`

Using FTBLib & FTB Utils 1.10.2-3.5.0, Baubles 1.10.2-1.3.9, among a bunch of other mods.

**Comment by macks2008** [comment]
Oh good, I'm not alone.
also, on a tangentially related note, I can't seem to give myself permission to use the command when running [spongeForge](https://www.spongepowered.org/downloads/spongeforge/stable/1.10.2) + [luckperms](https://forums.spongepowered.org/t/luckperms-an-advanced-permissions-plugin/14274). I give myself ftbu.command.inv but still get "you do not have permission to use that command". I realize this is probably on sponge's side of the fence, but I'll drop it here anyway. 

(And yes, before you ask, I'll make my own issue. I'm just dropping it here because it's convenient and will remove it once I make the independent issue)

**Comment by LatvianModder** [comment]
Probably fixed now
