### ISSUE TITLE
[Question] When does the backup timer start?

### ISSUE THREAD

**Issue by Adrian-Turjak** [LatvianModder/FTBUtilities#467]
Does the backup timer start on server startup, or does it check backups.json if present and continue from last backup?

Secondly, what happens when a backup is about to occur at a restart? Say a restart timer of 12, with backups set to occur every 4 hours. The 3rd would occur exactly at the same time as a restart. Would the restart wait for the backup, skip the backup, or would the backup occur right after the restart?

Trying to work out some sensible values for my server, so many thanks in advance. :)

**Comment by LatvianModder** [comment]
+ On server startup, but that will change soon, it will be at selected times, like 9:00AM and 9:00PM 
+ I have no idea. Most likely waits for the backup to finish. I thought about it a while ago, and for safety I changed the default config values so that they don't overlap, but once I rewrite the backup timer, I will add a safecheck, so it doesn't try to make backup and restart at the same time
