### ISSUE TITLE
Chunk loading doesn't work properly

### ISSUE THREAD

**Issue by LatvianModder** [LatvianModder/FTBUtilities#501]
Must be one of the oldest and most long-lasting issues in FTBU.

`- Why is it that hard?`
`- Because I have to load chunks without blocks and since none of the other mods do that, there is no example on how to do it properly AND make sure that chunks unload based on rank that players have`

Clean version of https://github.com/LatvianModder/FTBUtilities/issues/360, all other chunkloading related problems will be redirected here

**Comment by joshuagore** [comment]
Check out #504 this may be the root of this problem

**Comment by LatvianModder** [comment]
Yeah I noticed that. I will see if I can fix that, it's a Forge thing, it limits chunks in config, and I try to override that config, but maybe it changed

**Comment by LatvianModder** [comment]
Can someone test if it works now with http://mods.latmod.com/FTBLib/4.1.0/ and http://mods.latmod.com/FTBUtilities/4.1.0/ ?

**Comment by LatvianModder** [comment]
![image](https://user-images.githubusercontent.com/3844385/29361846-0b601806-8292-11e7-9ca7-6b880aaf26d4.png)
works for me! Except not with the first time, it takes 1 restart. So now I gotta find way to fix that

**Comment by merphle** [comment]
This seems to work correctly - tested in MC 1.12.1 in a brand new world with only Forge, FTBL, FTBU. Dedicated server. No additional configurations necessary.

**Comment by Vahtera** [comment]
Is it possible this bug makes this happen: https://github.com/McJty/RFTools/issues/1336 ?

**Comment by Vahtera** [comment]
/ftb loaded_chunks_list only shows Overworld and Nether, not any chunks on RFTools dimensions? Is this working as intended?

Also I have, according to the chunk claiming UI, loaded 44 chunks. 24 in overworld, 10 in Nether and 10 in RFTools dimension #9. that list only shows nether (10), overworld (24). So the amounts are correct, it just leaves out the RFTools dimension. Is that a cosmetic (whoops, the list doesn't display) bug, or is it not indeed chunkloading that dimension at all? (would explain that issue I referenced).

**Comment by LatvianModder** [comment]
RFTools dimensions don't work like normal dimensions and have always been a problem

**Comment by Vahtera** [comment]
In FTBUtilities, I disabled all chunk loaders (10 chunks) on the RFTools dimension then threw down two Extra Utilities Chunk Loader Wards (18 chunks). My server went from almost-constant 100% CPU usage to low 40s to high 50s. And all the problems I referenced in that RFTools issue disappeared. 

So FTBUtilities really does have an issue with RFTools dimensions (that Extra Utilities clearly doesn't).

**Comment by P3rf3ctXZer0** [comment]
I removed rftools and still crash

**Comment by LatvianModder** [comment]
From what I can tell, I think I fixed it in https://github.com/LatvianModder/FTBUtilities/commit/bf9c58a1ddac3bffd357572ab20eda021d15eb46

**Comment by Sadumon** [comment]
Using FTB Beyond 1.10 (FTBU 1.1x-3.6.5).

There seems to be an issue with how chunks that are only loaded due to FTBU are working.  If someone chunkloads a particular chunk that creates entities (e.g. a dropper to feed a botania endoflame or a mechanical user using bonemeal on a flower), those entities don't appear to be "processed."  By "processed", I mean they seem to be created fine but then just exist in the world.  Things that would normally interact with the entities (e.g. aforementioned endoflames, a vacuum chest trying to pick up the flowers, etc.) don't seem to activate.  When a player goes near that chunk, the entities begin to get processed, but the issue is that in the meantime whatever is creating the entities may have created thousands of entities.  When the server tries to start processing them, it results in the entire server freezing up.  If there are enough entities, it might freeze up to the point where it effectively locks the server whenever a player gets close enough for the chunk to be "properly" loaded.

We had a similar issue with immersive engineering chemical throwers that were throwing water -- if they were turned on but no player was near the loaded chunk, I would almost immediately see tens of thousands of entities created (count visible through TickProfiler's entity count).  When a player went nearby, it would freeze the server, but if the server eventually processed them all, they would all get cleaned up and then the server would function normally.

Based on another report (https://forum.feed-the-beast.com/threads/ftb-utilities-chunk-claiming-loading.222101/#post-1851824) it sounds like this issue is specific to FTBU's chunk loading.  I haven't been able to test it myself, but it should be relatively easy to set up a test.

**Comment by LatvianModder** [comment]
Gonna close this now, reopen if somebody can get it broken with latest releases
