### ISSUE TITLE
Chunk Loading not working offline?

### ISSUE THREAD

**Issue by k2gremlin** [LatvianModder/FTBUtilities#564]
Hello, I run a very small 3 person server and I am attempting to get chunk loading to continue to stay loaded even if a player is offline. I added "+ftbu.chunkloader.load_offline" to the player rank but it still does not work. Chunks unload almost instantly after the player logs off. Am I missing something here?

{
  "default_ranks": {
    "player": "player",
    "op": "op"
  },
  "ranks": {
    "player": {
      "parent": "builtin_player",
      "permissions": [
        "+ftbu.chunkloader.load_offline"
      ],
      "config": {}
    },
    "op": {
      "parent": "builtin_op",
      "syntax": "<&2$name&r> ",
      "permissions": [],
      "config": {}
    }
  }
}

**Comment by LatvianModder** [comment]
https://github.com/LatvianModder/FTBUtilities/issues/565

**Comment by k2gremlin** [comment]
Sorry if I mis-understood how these githubs issues work but it looks like you are falling this under issue #565. Are they related in some way? My chunkloading appears to work fine while in game. It only stop workined when offline. 

MC:Version 1.10.2
FTBServer: FTBserver-1.10.2-12.18.3.2477

**Comment by LatvianModder** [comment]
Oh 1.10.. Yeah I ain't fixing 1.10. But this issue is the same in its nature, because offline chunkloading should be enabled by default

**Comment by k2gremlin** [comment]
So I guess the only question I have now is what would I need to add to force it? Or is it just not an option for me?

**Comment by VioletRose** [comment]
> Yeah I ain't fixing 1.10.

But 1.10 is the version all of the stable, popular FTB mod packs are using. If your mod is named FTB Utilities and made for use with these mod packs, shouldn't you be supporting them?

**Comment by LatvianModder** [comment]
Are those modpacks still getting updates?

**Comment by VioletRose** [comment]
> Are those modpacks still getting updates?

Not to my knowledge, but even so much as a small unofficial patch would allow server owners to run it server-side to fix the broken behavior, instead of a critical part of the mod pack's functionality not working. And it is critical, because unloaded chunks in FTB Beyond doesn't just mean crops don't grow, it means power grids cease to function, and all other chunk loaders were disabled/removed specifically because FTB Utilities was seen as the best way to handle it. And it would be - if its settings were used reliably. On the server my friends have, we've repeatedly had RFTools dimensions lose power and kill players because the chunks they were powered in had come unloaded.
