### ISSUE TITLE
Missing features and other critics

### ISSUE THREAD

**Issue by chaos234** [LatvianModder/FTBUtilities#818]
I am not sure how long we should wait but the original FTBU seems not te be ported correctly from 1.7.10 to 1.12.2.

I know about this new FTBU-1.12.2 but this isn't that, what it has to be (my opinion) because why are we in need of a permission system? There are enough perm-mods out, also the 1.7.10 version was good as it was (not mentioning bugs for now).

Wyh? Because you have had a nice GUI to edit all the config values incl. max claims/chunkloads. Well, maybe in the chunkloading system was a bug or smth. which worked not like intended but after all it was the best version out there and now we have a mod which forces us to change things over a not wanted permission system?

I am not sure but if this is the intended way I don't think to use this mod in the near future anymore because if I want to have an eco server I would use sponge and essentials for this but FTBU for me was a mod which has had the ability to claim chunks and to load them and if the values are to low, then use /edit_config ftbu to rais them up which worked well.

And if I am correct it also added all of those /xu_* commands, like /xu_tps(_killmobs,_killall, and so on). I know that in 1.12.2 things have changed but what was then the reason to kickout these commands? They where not only nice but helpful too (looking at /xu_tps).

It would be nice to have the original 1.7.10 version ported to 1.12.2 as 1:1 instead of having this new FTBU which misses features and has wrong ones in it.

In 1.7.10 it was a nice and helpfull mod but now ... it isn't worth to be used. Sorry to say it the hard way but sometimes it is better to give a clear statement out as to go arround it.

Note that this is my opinion and my point of few. Other users may have other opinions and point of views to that which will clash with my one but this is just normal.

**Comment by ProxyNeko** [comment]
> I know about this new FTBU-1.12.2 but this isn't that, what it has to be (my opinion) because why are we in need of a permission system? There are enough perm-mods out, also the 1.7.10 version was good as it was (not mentioning bugs for now).

There are only a select few permissions mods out from what I can remember for forge but this built in one is (for me at least) one of the better-designed ones for forge, I see no issue with either using it or not using it, simple as.
Otherwise, there is always SpongeForge with LuckPerms but that takes a LOT more work than you seem to be willing to put in.

> I am not sure but if this is the intended way I don't think to use this mod in the near future anymore

Seeing this from the perspective of a mod developer I don't think (Or at least I wouldn't) I'd care about select people trying to say what is pretty much "Change things back or I won't use your mod!" So a general tip is don't be **that** guy...

> And if I am correct it also added all of those /xu_* commands, like /xu_tps(_killmobs,_killall, and so on). I know that in 1.12.2 things have changed but what was then the reason to kickout these commands? They where not only nice but helpful too (looking at /xu_tps).

tps: This was added into forge as `/forge tps`.
killall/killmobs: This is a vanilla command that takes args if you looked it up [here](https://minecraft.gamepedia.com/Commands/kill)
So there's that case closed.

> It would be nice to have the original 1.7.10 version ported to 1.12.2 as 1:1 instead of having this new FTBU which misses features and has wrong ones in it.

> In 1.7.10 it was a nice and helpfull mod but now ... it isn't worth to be used. Sorry to say it the hard way but sometimes it is better to give a clear statement out as to go arround it.

Mods change over time and some things get moved around. While I can see the use of some features changing and things being removed at first can be stressful for some people we just have to adapt to them rather than try and pressure people into keeping things the same.

So again don't be **that** guy...

**Comment by LatvianModder** [comment]
Things change, 1.12 version was never intended to be like 1.7 one
