### ISSUE TITLE
Make a wiki, please

### ISSUE THREAD

**Issue by MJRamon** [LatvianModder/FTBUtilities#82]
Please, write some documentation for this mod. I have to figure out it by downloading FTB modpacks and searching through configs and folders.

**Comment by LatvianModder** [comment]
Working on it here: https://github.com/LatvianModder/ModGuides/tree/ftbu
This will be ingame, but I will also figure out how to make it available online

**Comment by Goten87** [comment]
Why not just enable the wiki function on github for the mod ?

**Comment by popatop15** [comment]
I am also looking for some type of formal documentation. Maybe a list of features that are implemented/will be implemented. It gets confusing seeing cool things you can do with FTBU, and realizing it is not even a thing yet O_O

**Comment by hugeblank** [comment]
@LatvianModder Is there a Priority: URGENT label? This mod is confusing and rage inducing especially with no update changelog. I'm sitting in a 1.10.2 beta version with no teams GUI, no friends GUI and no claims GUI (all of which I got the mod for). The config menu is a buggy mess and there is NO documentation on ANY of it. I don't get how this has been overlooked for over 8 months seeing as this mod has been significantly changed since the 2 videos that are on the curseforge download page. Maybe it's worth considering reworking your documentation before adding more and worsening this more than high priority issue.

**Comment by LatvianModder** [comment]
Actually I have started working on guides
![Guides](http://ss.latmod.com/pc/2016-11-09_22.19.06.png)
It was just moved to mod itself. There will be web versions too, I really focus on getting a working version out rather than documenting old broken one
https://github.com/LatvianModder/FTBUtilities/tree/1.9/src/main/resources/assets/ftbu/guide

**Comment by hugeblank** [comment]
:DDD I'm thrilled!
