### ISSUE TITLE
Cannot disable journeymap claim integration, causes lag

### ISSUE THREAD

**Issue by TheNoseOfSauron** [LatvianModder/FTBUtilities#885]
Hi, me and several other members of my forge server are having an issue with the latest version of FTBUtils and Journeymap (FTBUtilities-5.3.0.54, journeymap-1.12.2-5.5.2). While journeymap integration for displaying claimed chunks can be disabled in client options, it does not work properly. It still occasionally displays the overlay, and moving around claimed chunks causes significant FPS drops.

**Comment by LatvianModder** [comment]
There is a client config, Inventory -> Client Settings -> FTBUtilities -> Enable JourneyMap Integration

**Comment by TheNoseOfSauron** [comment]
Sorry for not making myself clear.
I have disabled it in the client settings, yet the overlay still occasionally renders on the map, causing lag.
Other server members also experience this issue.

**Comment by LatvianModder** [comment]
Setting now requires restart, but should work

**Comment by Dimentive** [comment]
I’ve struggled with 20–40 fps in my base on good hardware for two months, and it was solved by simply disabling JourneyMap integration in FTB Utilities. It does _not_ cause lag; it causes frame rate issues.

When I disabled JourneyMap integration in FTBU, my frame rate in my base went from an average of 35 fps to 110+ fps. That’s an increase of 75 fps! It gave me more than triple my original frame rate. That’s ridiculous.

I’m super happy that disabling JourneyMap integration fixed my frame rate, as I can _finally_ play without utter frustration, but the fact that it was such a simple fix and no one told me about it kind of makes me irritated. I tried everything, and I mean ***everything***, to improve my frame rate, but in the end, after no success, I chalked it up to [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2), the pack I’m playing and have been playing for two months, just being horribly optimized (which it isn’t).

Well, turns out, FTB Utilities was at fault all along. Or JourneyMap. Or both. Not sure.
I was also playing with a friend, but now I’m playing alone because they had such poor performance. In the end, it was all because of one little option in the FTB Utilities settings, which is pretty unbelievable.

I ain’t mad, but maybe you should leave this disabled by default and add a warning in the config that it decreases frame rate? I appreciated that you fixed the bug that didn’t let players disable this in the first place, but it should probably not be enabled by default. Or is this just an issue that a few people face? I’ve never ever seen it mentioned before aside from this issue right here, so it might be.

I love the mod, by the way. 💙 I could never live without FTB Utilities and FTB Utilities: Backups.

**Comment by Dimentive** [comment]
@LatvianModder I’ve had a frame rate of 20–40 fps in my base on good hardware for a while now, and it was solved by simply disabling JourneyMap integration in FTB Utilities. When I disabled this option, my frame rate in my base went from an average of 35 fps to 70–110 fps. That’s a very significant increase in frames per second.

I’m really happy that I finally figured out what caused my frame rate issues after so much frustration, but I’d recommend that this option is disabled by default for anyone else who might have frame rate problems. Disabling the JourneyMap integration is unlikely to be something that people try when troubleshooting low frame rates, as it’s pretty unusual that some coloured circles on a minimap lower one’s frame rate to such an extent. For this reason, I would recommend that you set this option to false in future versions of FTB Utilities to prevent frustration for anyone else in the future. However, since I’ve never seen anyone say that this option could cause frame rate issues until I stumbled upon this GitHub issue via a Google search, it might not cause performance issues for everyone. I’m not sure.
